spring:
  application:
    name: lang-memory-docker

  # Database configuration for Docker
  datasource:
    url: jdbc:postgresql://postgres:5432/langmem
    driver-class-name: org.postgresql.Driver
    username: langmem
    password: langmem_password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# Lang Memory Configuration for Docker
langmem:
  vector-store:
    type: qdrant
    url: http://qdrant:6333
    collection: docker-memories
    options:
      similarity-threshold: 0.7

  llm:
    type: dashscope
    api-key: ${DASHSCOPE_API_KEY}
    model: qwen-turbo
    options:
      max-tokens: 1000
      temperature: 0.7

  embeddings:
    type: dashscope
    model: text-embedding-v1
    options:
      dimensions: 1536

  graph:
    type: neo4j
    uri: bolt://neo4j:7687
    username: neo4j
    password: password
    options:
      database: neo4j

  max-memories: 10000
  embedding-dimension: 1536
  similarity-threshold: 0.7

# Logging configuration for Docker
logging:
  level:
    com.langmem: INFO
    org.springframework: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /app/logs/lang-memory.log

# Server configuration for Docker
server:
  port: 8080
